#!/bin/bash

# Bash script that wraps around pkg-config, allows you to set the sysroot from the command line
# the pkg-config wrapper is needed to make pkg-config search in the proper location for include/library paths
# Which means the sysroot location can be passed from the toolchain file instead of being hardcoded here

SYSROOT=$1

export PKG_CONFIG_DIR=
export PKG_CONFIG_LIBDIR=${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/lib/arm-linux-gnueabihf/pkgconfig:${SYSROOT}/usr/share/pkgconfig
export PKG_CONFIG_SYSROOT_DIR=${SYSROOT}

exec pkg-config ${@:2}
